### ISSUE TITLE
Many PHP Notices, many more if using the node title as caption

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/mosaic_grid#16]
Hi @korontari,

first of all, many thanks for this cool module! :+1: 

When using it, I discovered several issues with PHP notices, though. Most of them, when using the node title as caption field, but also other ones.

To reproduce turn on error display on admin/config/development/logging. Notices appear when saving nodes, when adding a Mosaic Grid view, when editing it, when viewing it... Many times, many notices. (Undefined property, undefined index...)

They're not too hard to fix, PR coming soon. :wink:

**Comment by indigoxela** [comment]
And here's the [PR](https://github.com/backdrop-contrib/mosaic_grid/pull/17) for your kind review.

I hope, I catched all those PHP Notices with it.

**Comment by korontari** [comment]
Hello @indigoxela ! Thank you very much for catching these and making the PR. Looks like there are no more notices appear. I have created a release. If you have a spare minute to update the module and make sure it all works properly, I would appreciate that much. :)

**Comment by indigoxela** [comment]
Hi @korontari many thanks for the new release. I updated to version 1.x-2.1.2 and tested all sorts of functionality. Works like a charm, and no more notices. :+1:

**Comment by korontari** [comment]
Really glad to hear that, thank you very much for your help! :smiley:
