### ISSUE TITLE
Can't edit settings of Mosaic Grid format in a View

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/mosaic_grid#24]
After creating a Views block and setting it to the Mosaic Grid format, I'm not able to edit the format settings. The modal window for the settings doesn't open. In DBlog, I see the following related message:

> Error: [] operator not supported for strings in theme_container() (line 3653 of /path-to-site/core/includes/form.inc)

I was able to reproduce the issue on a vanilla Backdrop site created via https://backdropcms.org/demo:

- Backdrop 1.20.3
- PHP 7.2.34

**Comment by indigoxela** [comment]
Ooops, confirmed, the problem is in file views_plugin_style_mosaic_grid.inc

Bad:
```
    // Container for inline placement of the next two fields.
    $form['captions']['height'] = array(
      '#type' => 'container',
      '#attributes' => array (
        'class' => 'container-inline',
      ),
    );
```
"Class" should be an array.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop-contrib/mosaic_grid/pull/25) is available now.

**Comment by olafgrabienski** [comment]
Thanks for confirming, and for the PR! I've tested the fix on my site, works like a charm.

**Comment by korontari** [comment]
@olafgrabienski , @indigoxela , thank you very much for catching and quickly fixing the bug! I have rolled out a release with the fix.
