### ISSUE TITLE
Warning "Trying to access array offset on value of type null..."

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/mosaic_grid#28]
When switching from another views style plugin to mosaic grid in an aexisting view, a warning appears:
_"Trying to access array offset on value of type null in views_plugin_style_mosaic_grid->options_form() (line 95 of /modules/mosaic_grid/views_plugin_style_mosaic_grid.inc)."_

**Comment by argiepiano** [comment]
Try this to see if it solves it (in `views_plugin_style_mosaic_grid.inc`:

```php
    // Detect if text or title field is present, and add it to the options list.
    if (!empty($text_field = $this->get_first_non_excluded_text_field())) {
      $caption_options['text'] = $text_field['handler']->ui_name();
    }
```

**Comment by korontari** [comment]
@argiepiano , thank you for your quick help! That should work and I will include the fix in the next release (with some other improvements).
