### ISSUE TITLE
Preview in views

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/mosaic_grid#3]
Find the way to remove preview in views setup or make it work properly.

**Comment by stpaultim** [comment]
Making it work properly would be great, however I don't think it's that unusual for a special display like this to NOT work in views preview. I think that I have seen some modules that display a message in the preview block that says "this display will not work in preview mode."

**Comment by korontari** [comment]
Hello @stpaultim . Would you mind checking if the grid preview works in your setup? This is a link to a new version(branch): https://github.com/backdrop-contrib/mosaic_grid/tree/1.x-1.0.1

**Comment by Acertijo** [comment]
tested, it works in preview correctly

**Comment by stpaultim** [comment]
I can also confirm that preview is also working for me.

**Comment by korontari** [comment]
@Acertijo , @stpaultim , thank you!
