### ISSUE TITLE
Two blocks error when they are in the same page

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/mosaic_grid#5]
When insert two block of mosaic grid **in the same page**, it gets crazy... one of the blocks is unconfigured and if you try to move the scroll bar you can´t, it moves up down up down, for the moment i changed one of them to normal grid and it works.

**Comment by korontari** [comment]
@Acertijo, thank you for reporting this. I managed to reproduce the issue partially. Could you give me a bit more info so that I could reproduce it more precisely:
1. What layout were you using on the page?
2. Could you provide views configuration that you used for both mosaic grids?
3. What image sizes/styles you used for each of the grid?

**Comment by Acertijo** [comment]
hi, now you mention it i tried on test site with all in default mode, layout default (Moscone) also try with Boxton with the same result, theme default Basis 1.14.0, in views only image field, with default size of thumbnail of 100x100, i changed the sizes but give the same problem, the second block is showing the images without mosaic format, the first one is correct, another thing... the crazy scroll bar is only on Firefox i tried on chrome, opera and no crazy scrollbar

**Comment by korontari** [comment]
Hi @Acertijo . Thank you for the info! I did some explorations and I should be able to fix the issue with several mosaics on the same page. Regarding the 'crazy scrollbar' I will deal with it later as a separate issue in case it will still show up.

**Comment by korontari** [comment]
@Acertijo, could you install and test the new version: https://github.com/backdrop-contrib/mosaic_grid/tree/1.x-1.0.1
Let me know if it works in multiple blocks per page setup and also if the 'Firefox scrollbar' issue is still there?

**Comment by Acertijo** [comment]
@korontari it works now, no errors with multiple blocks in the same page and the scrollbar navigating is correct
thanks

**Comment by korontari** [comment]
@Acertijo , thank you for you feedback! I am really glad it worked out well. If you have a spare minute do you mind checking this issue as well: https://github.com/backdrop-contrib/mosaic_grid/issues/3 ?
